{
    "ssr_prefer": "{URL::SSRCanConnect($user, 0)}",
    "pre_user": {json_encode(URL::cloneUser($user))},
    "geetest_html": {json_encode($geetest_html)},
    "recaptcha_sitekey": "{$recaptcha_sitekey}",
    "enable_checkin": "{$config['enable_checkin']}",
    "enable_checkin_captcha": "{$config['enable_checkin_captcha']}",
    "enable_admin_contact": "{$config['enable_admin_contact']}",
    "admin_contact1": "{$config['admin_contact1']}",
    "admin_contact2": "{$config['admin_contact2']}",
    "admin_contact3": "{$config['admin_contact3']}",
    "captcha_provider": "{$config['captcha_provider']}",
    "subscribe_client": "{$config['subscribe_client']}",
    "subscribe_client_url": "{$config['subscribe_client_url']}",
    "client": {json_encode($getClient)},
    "userCenterClient": {json_encode($userCenterClient)},
    "ann": {json_encode($ann)},
    "class": "{$user->class}",
    "class_expire": "{$user->class_expire}",
    "money": "{$user->money}",
    "port": "{$user->port}",
    "passwd": "{$user->passwd}",
    "uuid": "{$user->uuid}",
    "method": "{$user->method}",
    "protocol": "{$user->protocol}",
    "obfs": "{$user->obfs}",
    "obfs_param": "{$user->obfs_param}",
    "expire_in":"{substr($user->expire_in, 0, 10)}",
    "node_connector":"{$user->node_connector}",
    "online_ip_count":"{$user->online_ip_count()}",
    "lastSsTime":"{$user->lastSsTime()}",
    "node_speedlimit":"{$user->node_speedlimit}",
    "valid_use_loop":"{$user->valid_use_loop()}",
    "transfer_enable":"{$user->transfer_enable}",
    "upload":"{$user->u}",
    "download":"{$user->d}",
    "last_day_t":"{$user->last_day_t}",
    "lastCheckInTime":"{$user->lastCheckInTime()}",
    "isAbleToCheckin":"{$user->isAbleToCheckin()}",
    "user_top_up":"{$user->get_top_up()}",
    "display_ios_class":"{$display_ios_class}",
    "display_ios_topup":"{$display_ios_topup}",
    "ios_account":"{$ios_account}",
    "ios_password":"{$ios_password}",
    "getUniversalSub":"{$getUniversalSub}",
    "subInfo":{json_encode($subInfo)},
    {function name=printClient items=null}
    "items":{json_encode($items)},
    {/function}
}


